---
title: Cornwallgeeks.Github.Io
timezone: UTC
collections:
  friends:
    title: Friends
    output: false
  organisers:
    title: Organisers
    output: false
  pages:
    title: Pages
    output: true
    permalink: "/:title/"
    post_dirs: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    excerpt_separator: "<!--more-->"
name: Cornwall Geeks
description:
  meta: A gathering of like minded people to talk about geeky stuff; programming,
    design, and gaming.
  subtitle: A gathering of like minded people to talk about geeky stuff; programming,
    design, and gaming.
author:
  name: Dan Reeves
  email: cornwallgeeks@gmail.com
  info: 
lang: en
incomplete: This page is incomplete. You can contribute on [GitHub](https://github.com/cornwallgeeks/cornwallgeeks.github.io)!
show-subtitle: true
display-social-icons: false
logo-image: 
theme-color-attr: "#00f0ff"
ms-tile-color: "#00f0ff"
theme-color: 0, 240, 255
text-color: 0, 0, 0
background-color: 255, 255, 255
display-author-post-page: true
display-author-front-page: true
date_format: "%b %-d, %Y"
nav-breaking-point: 595px
paginate: 3
display-next-prev-post: false
disqus-shortname: 
twitter: https://twitter.com/CornwallGeeks
github: https://github.com/CornwallGeeks
var_on_the_web: On the web
var_read: Read
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message
paginate_path: "/:num/"
permalink: pretty
gems:
- jekyll-mentions
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-avatar
